package com.xrdocker.whitemouse.persistent.entity;

public class JvmOederWithBLOBs extends JvmOeder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.details
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.demo_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private String demoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.javap_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private String javapCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.details
     *
     * @return the value of jvm_oeder.details
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.details
     *
     * @param details the value for jvm_oeder.details
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.demo_code
     *
     * @return the value of jvm_oeder.demo_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public String getDemoCode() {
        return demoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.demo_code
     *
     * @param demoCode the value for jvm_oeder.demo_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setDemoCode(String demoCode) {
        this.demoCode = demoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.javap_code
     *
     * @return the value of jvm_oeder.javap_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public String getJavapCode() {
        return javapCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.javap_code
     *
     * @param javapCode the value for jvm_oeder.javap_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setJavapCode(String javapCode) {
        this.javapCode = javapCode;
    }
}