package com.xrdocker.whitemouse.persistent.entity;

import java.sql.Timestamp;

public class JvmOeder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.id
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.order_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.mnemonic
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private String mnemonic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.desc
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.creat_time
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private Timestamp creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvm_oeder.update_time
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.id
     *
     * @return the value of jvm_oeder.id
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.id
     *
     * @param id the value for jvm_oeder.id
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.order_code
     *
     * @return the value of jvm_oeder.order_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.order_code
     *
     * @param orderCode the value for jvm_oeder.order_code
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.mnemonic
     *
     * @return the value of jvm_oeder.mnemonic
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public String getMnemonic() {
        return mnemonic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.mnemonic
     *
     * @param mnemonic the value for jvm_oeder.mnemonic
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setMnemonic(String mnemonic) {
        this.mnemonic = mnemonic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.desc
     *
     * @return the value of jvm_oeder.desc
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.desc
     *
     * @param desc the value for jvm_oeder.desc
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.creat_time
     *
     * @return the value of jvm_oeder.creat_time
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public Timestamp getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.creat_time
     *
     * @param creatTime the value for jvm_oeder.creat_time
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setCreatTime(Timestamp creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvm_oeder.update_time
     *
     * @return the value of jvm_oeder.update_time
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvm_oeder.update_time
     *
     * @param updateTime the value for jvm_oeder.update_time
     *
     * @mbggenerated Mon Jun 03 17:11:39 CST 2019
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}