#jdbc:
#   driverClass:
#   url: mysql://211.149.142.55:3306/dkmouse?useUnicode=true&characterEncoding=UTF-8
#   username: root
#   password: xr2ln1314

c3p0:
   maxPoolSize: 20
   minPoolSize: 2
   initialPoolSize: 2
   maxIdleTime: 60
   checkoutTimeout: 5000
   acquireIncrement: 2
   acquireRetryAttempts: 0
   acquireRetryDelay: 1000
   autoCommitOnClose: false
   automaticTestTable: C3P0_AUTO_TEST
   breakAfterAcquireFailure: false
   idleConnectionTestPeriod: 60
   testConnectionOnCheckin: false
   testConnectionOnCheckout: false

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: mysql://211.149.142.55:3306/dkmouse?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: xr2ln1314